<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permission')->delete();
        
        \DB::table('permission')->insert(array (
            0 => 
            array (
                'id' => '9c143c88-b996-4638-8a44-2696abccfd2a',
                'slug' => 'menu.create',
                'nama' => 'Menampilkan form tambah Menu',
                'action' => 'create',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'id' => '9c143c88-bc38-4705-93c2-e026392f96f9',
                'slug' => 'menu.destroy',
                'nama' => 'Menghapus Menu',
                'action' => 'destroy',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'id' => '9c143c88-bca4-406a-a587-f08de3200a5f',
                'slug' => 'menu.edit',
                'nama' => 'Menampilkan form edit Menu',
                'action' => 'edit',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'id' => '9c143c88-bcfc-4513-b7bc-e0ee069131d7',
                'slug' => 'menu.index',
                'nama' => 'Melihat daftar Menu',
                'action' => 'index',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'id' => '9c143c88-bd54-40e2-8b34-386e7f0e1aa4',
                'slug' => 'menu.show',
                'nama' => 'Menampilkan detail Menu',
                'action' => 'show',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'id' => '9c143c88-bdaf-4548-bf26-e64e152fcf20',
                'slug' => 'menu.store',
                'nama' => 'Menyimpan form tambah Menu',
                'action' => 'store',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'id' => '9c143c88-be19-44fd-a9c7-720abce3da06',
                'slug' => 'menu.update',
                'nama' => 'Menyimpan form edit Menu',
                'action' => 'update',
                'group' => 'menu',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            7 => 
            array (
                'id' => '9c143c88-be66-44f1-993d-5e67a8b0b976',
                'slug' => 'menugroup.create',
                'nama' => 'Menampilkan form tambah Menugroup',
                'action' => 'create',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            8 => 
            array (
                'id' => '9c143c88-bec4-4788-9a24-41d787f1cc45',
                'slug' => 'menugroup.destroy',
                'nama' => 'Menghapus Menugroup',
                'action' => 'destroy',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            9 => 
            array (
                'id' => '9c143c88-bf18-4d75-9618-5f124a6a5903',
                'slug' => 'menugroup.edit',
                'nama' => 'Menampilkan form edit Menugroup',
                'action' => 'edit',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            10 => 
            array (
                'id' => '9c143c88-bf78-45d8-bdbc-9972f51cad3f',
                'slug' => 'menugroup.index',
                'nama' => 'Melihat daftar Menugroup',
                'action' => 'index',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            11 => 
            array (
                'id' => '9c143c88-bfd6-496b-b680-a61c0e068ad8',
                'slug' => 'menugroup.show',
                'nama' => 'Menampilkan detail Menugroup',
                'action' => 'show',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            12 => 
            array (
                'id' => '9c143c88-c039-4338-90f8-99dbbf21d7b6',
                'slug' => 'menugroup.store',
                'nama' => 'Menyimpan form tambah Menugroup',
                'action' => 'store',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            13 => 
            array (
                'id' => '9c143c88-c0b2-4478-94d7-310a808beea7',
                'slug' => 'menugroup.update',
                'nama' => 'Menyimpan form edit Menugroup',
                'action' => 'update',
                'group' => 'menugroup',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            14 => 
            array (
                'id' => '9c143c88-c11d-4716-9268-2e05212e5199',
                'slug' => 'module.create',
                'nama' => 'Menampilkan form tambah Module',
                'action' => 'create',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            15 => 
            array (
                'id' => '9c143c88-c180-45ef-a8d1-7de0d4c8eb46',
                'slug' => 'module.destroy',
                'nama' => 'Menghapus Module',
                'action' => 'destroy',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            16 => 
            array (
                'id' => '9c143c88-c1f5-44c5-baf4-c530701657b5',
                'slug' => 'module.edit',
                'nama' => 'Menampilkan form edit Module',
                'action' => 'edit',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            17 => 
            array (
                'id' => '9c143c88-c2c5-4bc9-bd35-a7913968bd52',
                'slug' => 'module.index',
                'nama' => 'Melihat daftar Module',
                'action' => 'index',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            18 => 
            array (
                'id' => '9c143c88-c322-47d3-8b90-6ae20730aa02',
                'slug' => 'module.show',
                'nama' => 'Menampilkan detail Module',
                'action' => 'show',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            19 => 
            array (
                'id' => '9c143c88-c388-4f20-9d74-a327cd2cbaf0',
                'slug' => 'module.store',
                'nama' => 'Menyimpan form tambah Module',
                'action' => 'store',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            20 => 
            array (
                'id' => '9c143c88-c3fa-4fac-a19e-8e5fa1a92295',
                'slug' => 'module.update',
                'nama' => 'Menyimpan form edit Module',
                'action' => 'update',
                'group' => 'module',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            21 => 
            array (
                'id' => '9c143c88-c461-4192-8594-8f8761a0ac2b',
                'slug' => 'permission.create',
                'nama' => 'Menampilkan form tambah Permission',
                'action' => 'create',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            22 => 
            array (
                'id' => '9c143c88-c4c2-4366-a231-887eb37d9f56',
                'slug' => 'permission.destroy',
                'nama' => 'Menghapus Permission',
                'action' => 'destroy',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            23 => 
            array (
                'id' => '9c143c88-c53c-4169-9006-3d8e24764851',
                'slug' => 'permission.edit',
                'nama' => 'Menampilkan form edit Permission',
                'action' => 'edit',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            24 => 
            array (
                'id' => '9c143c88-c5a0-42a5-aa92-e75111720ffa',
                'slug' => 'permission.index',
                'nama' => 'Melihat daftar Permission',
                'action' => 'index',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            25 => 
            array (
                'id' => '9c143c88-c60a-4fcf-98cd-3030d67dd745',
                'slug' => 'permission.show',
                'nama' => 'Menampilkan detail Permission',
                'action' => 'show',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            26 => 
            array (
                'id' => '9c143c88-c668-41ae-91fd-7836ce41e978',
                'slug' => 'permission.store',
                'nama' => 'Menyimpan form tambah Permission',
                'action' => 'store',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            27 => 
            array (
                'id' => '9c143c88-c6cb-48e9-99ac-e8e44b2e0c04',
                'slug' => 'permission.update',
                'nama' => 'Menyimpan form edit Permission',
                'action' => 'update',
                'group' => 'permission',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            28 => 
            array (
                'id' => '9c143c88-cd0d-455f-a5f2-1bd044f5fe71',
                'slug' => 'role.create',
                'nama' => 'Menampilkan form tambah Role',
                'action' => 'create',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            29 => 
            array (
                'id' => '9c143c88-cd60-44c7-a1f2-6b22b9dfbe60',
                'slug' => 'role.destroy',
                'nama' => 'Menghapus Role',
                'action' => 'destroy',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            30 => 
            array (
                'id' => '9c143c88-cdb0-43f0-b45e-a0075e011efe',
                'slug' => 'role.edit',
                'nama' => 'Menampilkan form edit Role',
                'action' => 'edit',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            31 => 
            array (
                'id' => '9c143c88-ce0d-44c4-bf83-923a5e3ed3d8',
                'slug' => 'role.index',
                'nama' => 'Melihat daftar Role',
                'action' => 'index',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            32 => 
            array (
                'id' => '9c143c88-ce63-42f9-9e4d-b2412bacde79',
                'slug' => 'role.permission.update',
                'nama' => 'Menyimpan form edit Role Permission ',
                'action' => 'update',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            33 => 
            array (
                'id' => '9c143c88-ceb7-437c-a417-f7506d1d92bf',
                'slug' => 'role.show',
                'nama' => 'Menampilkan detail Role',
                'action' => 'show',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            34 => 
            array (
                'id' => '9c143c88-cef9-4582-96b3-f7affd56ec22',
                'slug' => 'role.store',
                'nama' => 'Menyimpan form tambah Role',
                'action' => 'store',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            35 => 
            array (
                'id' => '9c143c88-cf3b-4bce-8c18-44df5b41e35a',
                'slug' => 'role.update',
                'nama' => 'Menyimpan form edit Role',
                'action' => 'update',
                'group' => 'role',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            36 => 
            array (
                'id' => '9c143c88-d157-4c5c-b2a4-12d6b674a6c2',
                'slug' => 'user.create',
                'nama' => 'Menampilkan form tambah User',
                'action' => 'create',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            37 => 
            array (
                'id' => '9c143c88-d1ac-4ec9-a099-108654b86be9',
                'slug' => 'user.destroy',
                'nama' => 'Menghapus User',
                'action' => 'destroy',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            38 => 
            array (
                'id' => '9c143c88-d1fe-4c64-a45c-a0eefc3d65a3',
                'slug' => 'user.edit',
                'nama' => 'Menampilkan form edit User',
                'action' => 'edit',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            39 => 
            array (
                'id' => '9c143c88-d243-4623-bdf8-c81eba2eab32',
                'slug' => 'user.index',
                'nama' => 'Melihat daftar User',
                'action' => 'index',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            40 => 
            array (
                'id' => '9c143c88-d280-4222-9f4b-b6760f2849e5',
                'slug' => 'user.show',
                'nama' => 'Menampilkan detail User',
                'action' => 'show',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            41 => 
            array (
                'id' => '9c143c88-d2bd-4ddd-825d-66ee681985b6',
                'slug' => 'user.store',
                'nama' => 'Menyimpan form tambah User',
                'action' => 'store',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            42 => 
            array (
                'id' => '9c143c88-d2f9-493b-a346-ce5d252032de',
                'slug' => 'user.update',
                'nama' => 'Menyimpan form edit User',
                'action' => 'update',
                'group' => 'user',
                'description' => NULL,
                'created_at' => '2024-05-19 08:28:08',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            43 => 
            array (
                'id' => '9c17bd8d-5f23-45e6-8adf-e012ee161ac6',
                'slug' => 'log.create',
                'nama' => 'Menampilkan form tambah Log',
                'action' => 'create',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            44 => 
            array (
                'id' => '9c17bd8d-630c-403d-a0da-147212e95f0d',
                'slug' => 'log.destroy',
                'nama' => 'Menghapus Log',
                'action' => 'destroy',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            45 => 
            array (
                'id' => '9c17bd8d-6376-48ab-8357-f61f4ead4088',
                'slug' => 'log.edit',
                'nama' => 'Menampilkan form edit Log',
                'action' => 'edit',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            46 => 
            array (
                'id' => '9c17bd8d-63d8-41e5-b5c7-177d26ba4594',
                'slug' => 'log.index',
                'nama' => 'Melihat daftar Log',
                'action' => 'index',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            47 => 
            array (
                'id' => '9c17bd8d-6446-439c-a48f-45507b2eee28',
                'slug' => 'log.show',
                'nama' => 'Menampilkan detail Log',
                'action' => 'show',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            48 => 
            array (
                'id' => '9c17bd8d-64af-4049-9779-ce94a0e143e7',
                'slug' => 'log.store',
                'nama' => 'Menyimpan form tambah Log',
                'action' => 'store',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            49 => 
            array (
                'id' => '9c17bd8d-6526-4026-ba72-e32a8c5bc7ed',
                'slug' => 'log.update',
                'nama' => 'Menyimpan form edit Log',
                'action' => 'update',
                'group' => 'log',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            50 => 
            array (
                'id' => '9c17bd8d-6f14-4a97-878b-d71fc5187296',
                'slug' => 'permissionrole.create',
                'nama' => 'Menampilkan form tambah Permissionrole',
                'action' => 'create',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            51 => 
            array (
                'id' => '9c17bd8d-6f99-4fc5-9350-0a6858250d2d',
                'slug' => 'permissionrole.destroy',
                'nama' => 'Menghapus Permissionrole',
                'action' => 'destroy',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            52 => 
            array (
                'id' => '9c17bd8d-6ff3-4ded-a55e-0220150b9066',
                'slug' => 'permissionrole.edit',
                'nama' => 'Menampilkan form edit Permissionrole',
                'action' => 'edit',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            53 => 
            array (
                'id' => '9c17bd8d-704f-438d-92ee-8446febd8063',
                'slug' => 'permissionrole.index',
                'nama' => 'Melihat daftar Permissionrole',
                'action' => 'index',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            54 => 
            array (
                'id' => '9c17bd8d-70ab-4810-8303-2f0c5b4e7dc2',
                'slug' => 'permissionrole.show',
                'nama' => 'Menampilkan detail Permissionrole',
                'action' => 'show',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            55 => 
            array (
                'id' => '9c17bd8d-710f-44f7-af69-c4adbe9559cc',
                'slug' => 'permissionrole.store',
                'nama' => 'Menyimpan form tambah Permissionrole',
                'action' => 'store',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            56 => 
            array (
                'id' => '9c17bd8d-7184-4add-bc53-9b39b04eb52c',
                'slug' => 'permissionrole.update',
                'nama' => 'Menyimpan form edit Permissionrole',
                'action' => 'update',
                'group' => 'permissionrole',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            57 => 
            array (
                'id' => '9c17bd8d-7600-40c2-b2d3-c4bd0a1031d3',
                'slug' => 'roleuser.create',
                'nama' => 'Menampilkan form tambah Roleuser',
                'action' => 'create',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            58 => 
            array (
                'id' => '9c17bd8d-765e-4df8-a792-b0024dfef955',
                'slug' => 'roleuser.destroy',
                'nama' => 'Menghapus Roleuser',
                'action' => 'destroy',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            59 => 
            array (
                'id' => '9c17bd8d-76a3-47fa-87f6-05630f2f8cb0',
                'slug' => 'roleuser.edit',
                'nama' => 'Menampilkan form edit Roleuser',
                'action' => 'edit',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            60 => 
            array (
                'id' => '9c17bd8d-76eb-4d18-b0f8-d0e337f961d2',
                'slug' => 'roleuser.index',
                'nama' => 'Melihat daftar Roleuser',
                'action' => 'index',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            61 => 
            array (
                'id' => '9c17bd8d-7748-4968-8e71-f502e510d34e',
                'slug' => 'roleuser.show',
                'nama' => 'Menampilkan detail Roleuser',
                'action' => 'show',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            62 => 
            array (
                'id' => '9c17bd8d-7794-44e0-8bad-db390fb71ca6',
                'slug' => 'roleuser.store',
                'nama' => 'Menyimpan form tambah Roleuser',
                'action' => 'store',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            63 => 
            array (
                'id' => '9c17bd8d-77dd-4a61-b170-2e1550b80456',
                'slug' => 'roleuser.update',
                'nama' => 'Menyimpan form edit Roleuser',
                'action' => 'update',
                'group' => 'roleuser',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            64 => 
            array (
                'id' => '9c17bd8d-781f-41a6-b767-ac5c8ba9979f',
                'slug' => 'scope.create',
                'nama' => 'Menampilkan form tambah Scope',
                'action' => 'create',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            65 => 
            array (
                'id' => '9c17bd8d-7861-431e-ba77-cc93cefea6b9',
                'slug' => 'scope.destroy',
                'nama' => 'Menghapus Scope',
                'action' => 'destroy',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            66 => 
            array (
                'id' => '9c17bd8d-78ac-43d7-bc59-265a74053e6d',
                'slug' => 'scope.edit',
                'nama' => 'Menampilkan form edit Scope',
                'action' => 'edit',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            67 => 
            array (
                'id' => '9c17bd8d-78fa-4a35-b2f0-c7122ccee622',
                'slug' => 'scope.index',
                'nama' => 'Melihat daftar Scope',
                'action' => 'index',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            68 => 
            array (
                'id' => '9c17bd8d-794b-45a4-9653-8d1e00c152b6',
                'slug' => 'scope.show',
                'nama' => 'Menampilkan detail Scope',
                'action' => 'show',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            69 => 
            array (
                'id' => '9c17bd8d-7994-4785-9830-d5cd3c9dee77',
                'slug' => 'scope.store',
                'nama' => 'Menyimpan form tambah Scope',
                'action' => 'store',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            70 => 
            array (
                'id' => '9c17bd8d-79d8-49b3-b288-3021c333a638',
                'slug' => 'scope.update',
                'nama' => 'Menyimpan form edit Scope',
                'action' => 'update',
                'group' => 'scope',
                'description' => NULL,
                'created_at' => '2024-05-21 02:16:23',
                'updated_at' => '2024-05-21 02:16:23',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            71 => 
            array (
                'id' => '9cbb29d4-dfc1-499b-aee9-8fbee56c0125',
                'slug' => 'mapel.index',
                'nama' => 'Melihat daftar Mapel',
                'action' => 'index',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            72 => 
            array (
                'id' => '9cbb29d5-03c0-4140-acc8-24c59721c82b',
                'slug' => 'mapel.create',
                'nama' => 'Menampilkan form tambah Mapel',
                'action' => 'create',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            73 => 
            array (
                'id' => '9cbb29d5-0499-488f-8ea6-5347a91068eb',
                'slug' => 'mapel.store',
                'nama' => 'Menyimpan form tambah Mapel',
                'action' => 'store',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            74 => 
            array (
                'id' => '9cbb29d5-05c3-488c-ab16-1f9513fa676c',
                'slug' => 'mapel.show',
                'nama' => 'Menampilkan detail Mapel',
                'action' => 'show',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            75 => 
            array (
                'id' => '9cbb29d5-069c-4bb8-8600-661ed38b8eb9',
                'slug' => 'mapel.edit',
                'nama' => 'Menampilkan form edit Mapel',
                'action' => 'edit',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            76 => 
            array (
                'id' => '9cbb29d5-075a-4f2b-b794-cd589e280f3b',
                'slug' => 'mapel.update',
                'nama' => 'Menyimpan form edit Mapel',
                'action' => 'update',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            77 => 
            array (
                'id' => '9cbb29d5-080c-4779-9c44-a594b70cac2b',
                'slug' => 'mapel.destroy',
                'nama' => 'Menghapus Mapel',
                'action' => 'destroy',
                'group' => 'mapel',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:06',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            78 => 
            array (
                'id' => '9cbb29dd-4d11-4df6-aee8-b7573be32acd',
                'slug' => 'kelas.index',
                'nama' => 'Melihat daftar Kelas',
                'action' => 'index',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            79 => 
            array (
                'id' => '9cbb29dd-511f-40c3-9c03-7ad77334ad03',
                'slug' => 'kelas.create',
                'nama' => 'Menampilkan form tambah Kelas',
                'action' => 'create',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            80 => 
            array (
                'id' => '9cbb29dd-51f0-4272-bdca-bc4936b1754b',
                'slug' => 'kelas.store',
                'nama' => 'Menyimpan form tambah Kelas',
                'action' => 'store',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            81 => 
            array (
                'id' => '9cbb29dd-52e2-42b1-a50a-73b2a56906d3',
                'slug' => 'kelas.show',
                'nama' => 'Menampilkan detail Kelas',
                'action' => 'show',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            82 => 
            array (
                'id' => '9cbb29dd-54a5-4255-bd70-22b9acb97d96',
                'slug' => 'kelas.edit',
                'nama' => 'Menampilkan form edit Kelas',
                'action' => 'edit',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            83 => 
            array (
                'id' => '9cbb29dd-5584-4b64-bebc-9e21223bbcc3',
                'slug' => 'kelas.update',
                'nama' => 'Menyimpan form edit Kelas',
                'action' => 'update',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            84 => 
            array (
                'id' => '9cbb29dd-568c-4e98-a7c5-b58e772eac5c',
                'slug' => 'kelas.destroy',
                'nama' => 'Menghapus Kelas',
                'action' => 'destroy',
                'group' => 'kelas',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            85 => 
            array (
                'id' => '9cbb29ea-8466-409f-81f0-9f0d1f3daaaa',
                'slug' => 'materi.index',
                'nama' => 'Melihat daftar Materi',
                'action' => 'index',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            86 => 
            array (
                'id' => '9cbb29ea-897d-4731-9fb0-22cecd5be532',
                'slug' => 'materi.create',
                'nama' => 'Menampilkan form tambah Materi',
                'action' => 'create',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            87 => 
            array (
                'id' => '9cbb29ea-8a6b-4540-b49d-797243aff366',
                'slug' => 'materi.store',
                'nama' => 'Menyimpan form tambah Materi',
                'action' => 'store',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            88 => 
            array (
                'id' => '9cbb29ea-8b87-41ee-80b4-616dcf3f51ad',
                'slug' => 'materi.show',
                'nama' => 'Menampilkan detail Materi',
                'action' => 'show',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            89 => 
            array (
                'id' => '9cbb29ea-8cae-41d7-8f80-ab3f025921c8',
                'slug' => 'materi.edit',
                'nama' => 'Menampilkan form edit Materi',
                'action' => 'edit',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            90 => 
            array (
                'id' => '9cbb29ea-8d89-43dd-ac24-77160a3f957b',
                'slug' => 'materi.update',
                'nama' => 'Menyimpan form edit Materi',
                'action' => 'update',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            91 => 
            array (
                'id' => '9cbb29ea-8e55-4778-a8fe-5fe491115034',
                'slug' => 'materi.destroy',
                'nama' => 'Menghapus Materi',
                'action' => 'destroy',
                'group' => 'materi',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:20',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            92 => 
            array (
                'id' => '9cbb2a01-ded7-46bc-9466-0d53a881a263',
                'slug' => 'assigments.index',
                'nama' => 'Melihat daftar Assigments',
                'action' => 'index',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            93 => 
            array (
                'id' => '9cbb2a01-e2e2-4c4c-abae-e5579fb116e4',
                'slug' => 'assigments.create',
                'nama' => 'Menampilkan form tambah Assigments',
                'action' => 'create',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            94 => 
            array (
                'id' => '9cbb2a01-e477-433f-9e90-1882830bf308',
                'slug' => 'assigments.store',
                'nama' => 'Menyimpan form tambah Assigments',
                'action' => 'store',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            95 => 
            array (
                'id' => '9cbb2a01-e57e-43df-b6da-926e8f7f664a',
                'slug' => 'assigments.show',
                'nama' => 'Menampilkan detail Assigments',
                'action' => 'show',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            96 => 
            array (
                'id' => '9cbb2a01-e6cc-4c0b-ab48-cef86aa33f18',
                'slug' => 'assigments.edit',
                'nama' => 'Menampilkan form edit Assigments',
                'action' => 'edit',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            97 => 
            array (
                'id' => '9cbb2a01-e7fa-4a62-b3e3-a4cfb05b7c1a',
                'slug' => 'assigments.update',
                'nama' => 'Menyimpan form edit Assigments',
                'action' => 'update',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            98 => 
            array (
                'id' => '9cbb2a01-e8e9-4ba1-83e3-f4335f6002be',
                'slug' => 'assigments.destroy',
                'nama' => 'Menghapus Assigments',
                'action' => 'destroy',
                'group' => 'assigments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:35',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            99 => 
            array (
                'id' => '9cbb2a0c-1d96-4849-855a-96a0e969b239',
                'slug' => 'submissions.index',
                'nama' => 'Melihat daftar Submissions',
                'action' => 'index',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            100 => 
            array (
                'id' => '9cbb2a0c-2367-403a-b59a-043d9e28962a',
                'slug' => 'submissions.create',
                'nama' => 'Menampilkan form tambah Submissions',
                'action' => 'create',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            101 => 
            array (
                'id' => '9cbb2a0c-244d-44c3-8a70-2c18e44e9193',
                'slug' => 'submissions.store',
                'nama' => 'Menyimpan form tambah Submissions',
                'action' => 'store',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            102 => 
            array (
                'id' => '9cbb2a0c-2559-4bd2-8923-8007f25f7f22',
                'slug' => 'submissions.show',
                'nama' => 'Menampilkan detail Submissions',
                'action' => 'show',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            103 => 
            array (
                'id' => '9cbb2a0c-26d6-4ab8-a378-dfc44371de2a',
                'slug' => 'submissions.edit',
                'nama' => 'Menampilkan form edit Submissions',
                'action' => 'edit',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            104 => 
            array (
                'id' => '9cbb2a0c-2841-4bbc-8c4d-ca37e701dc49',
                'slug' => 'submissions.update',
                'nama' => 'Menyimpan form edit Submissions',
                'action' => 'update',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:53',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            105 => 
            array (
                'id' => '9cbb2a0c-292b-44f2-89c0-6344fb156e0e',
                'slug' => 'submissions.destroy',
                'nama' => 'Menghapus Submissions',
                'action' => 'destroy',
                'group' => 'submissions',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:42',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            106 => 
            array (
                'id' => '9cbb2a23-0b8a-45e6-af06-3d8eb486a649',
                'slug' => 'enrollments.index',
                'nama' => 'Melihat daftar Enrollments',
                'action' => 'index',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            107 => 
            array (
                'id' => '9cbb2a23-0fa7-47dd-a30b-59de116400de',
                'slug' => 'enrollments.create',
                'nama' => 'Menampilkan form tambah Enrollments',
                'action' => 'create',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            108 => 
            array (
                'id' => '9cbb2a23-10f1-4521-b1fe-46171d6e962a',
                'slug' => 'enrollments.store',
                'nama' => 'Menyimpan form tambah Enrollments',
                'action' => 'store',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            109 => 
            array (
                'id' => '9cbb2a23-11e7-439b-b176-7b2f5ed638bc',
                'slug' => 'enrollments.show',
                'nama' => 'Menampilkan detail Enrollments',
                'action' => 'show',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            110 => 
            array (
                'id' => '9cbb2a23-1308-42cc-b3b9-958540a3d6f1',
                'slug' => 'enrollments.edit',
                'nama' => 'Menampilkan form edit Enrollments',
                'action' => 'edit',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            111 => 
            array (
                'id' => '9cbb2a23-1444-448b-b833-8dd17f1f93c7',
                'slug' => 'enrollments.update',
                'nama' => 'Menyimpan form edit Enrollments',
                'action' => 'update',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            112 => 
            array (
                'id' => '9cbb2a23-1567-484b-bd42-45e53890ff1e',
                'slug' => 'enrollments.destroy',
                'nama' => 'Menghapus Enrollments',
                'action' => 'destroy',
                'group' => 'enrollments',
                'description' => NULL,
                'created_at' => '2024-08-10 07:59:57',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            113 => 
            array (
                'id' => '9cbb2a38-c4ee-47a1-9b00-3ab15f407559',
                'slug' => 'announcements.index',
                'nama' => 'Melihat daftar Announcements',
                'action' => 'index',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            114 => 
            array (
                'id' => '9cbb2a38-c93c-4e0b-8073-5384b24797bb',
                'slug' => 'announcements.create',
                'nama' => 'Menampilkan form tambah Announcements',
                'action' => 'create',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            115 => 
            array (
                'id' => '9cbb2a38-ca24-4d76-8fb9-67e3468911d6',
                'slug' => 'announcements.store',
                'nama' => 'Menyimpan form tambah Announcements',
                'action' => 'store',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            116 => 
            array (
                'id' => '9cbb2a38-cb30-4bed-ada8-48a0781d8692',
                'slug' => 'announcements.show',
                'nama' => 'Menampilkan detail Announcements',
                'action' => 'show',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            117 => 
            array (
                'id' => '9cbb2a38-cc78-44ee-881d-5bfb1a7cdfb5',
                'slug' => 'announcements.edit',
                'nama' => 'Menampilkan form edit Announcements',
                'action' => 'edit',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            118 => 
            array (
                'id' => '9cbb2a38-cd47-44fe-8945-9dbe3eaefb06',
                'slug' => 'announcements.update',
                'nama' => 'Menyimpan form edit Announcements',
                'action' => 'update',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            119 => 
            array (
                'id' => '9cbb2a38-ce2e-4ac8-9bc3-3ec748cb94a4',
                'slug' => 'announcements.destroy',
                'nama' => 'Menghapus Announcements',
                'action' => 'destroy',
                'group' => 'announcements',
                'description' => NULL,
                'created_at' => '2024-08-10 08:00:11',
                'updated_at' => '2024-08-10 08:12:52',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            120 => 
            array (
                'id' => '9cbb596a-fca4-40ee-878e-0a97d71c47c5',
                'slug' => 'assignments.index',
                'nama' => 'Melihat daftar Assignments',
                'action' => 'index',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            121 => 
            array (
                'id' => '9cbb596b-0f4e-4528-999d-61c4a887948e',
                'slug' => 'assignments.create',
                'nama' => 'Menampilkan form tambah Assignments',
                'action' => 'create',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            122 => 
            array (
                'id' => '9cbb596b-10db-47c7-ac44-aea3c453cbd1',
                'slug' => 'assignments.store',
                'nama' => 'Menyimpan form tambah Assignments',
                'action' => 'store',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            123 => 
            array (
                'id' => '9cbb596b-11da-41fc-8249-b05720bbbd6a',
                'slug' => 'assignments.show',
                'nama' => 'Menampilkan detail Assignments',
                'action' => 'show',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            124 => 
            array (
                'id' => '9cbb596b-130d-4b65-8976-b718a94ea8b0',
                'slug' => 'assignments.edit',
                'nama' => 'Menampilkan form edit Assignments',
                'action' => 'edit',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            125 => 
            array (
                'id' => '9cbb596b-13f7-4230-b713-522743936520',
                'slug' => 'assignments.update',
                'nama' => 'Menyimpan form edit Assignments',
                'action' => 'update',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            126 => 
            array (
                'id' => '9cbb596b-14d7-4f96-b6ca-c0e95cbea878',
                'slug' => 'assignments.destroy',
                'nama' => 'Menghapus Assignments',
                'action' => 'destroy',
                'group' => 'assignments',
                'description' => NULL,
                'created_at' => '2024-08-10 10:12:10',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            127 => 
            array (
                'id' => '9cc1a0af-4e77-4728-8be4-3eb878261b75',
                'slug' => 'guru.index',
                'nama' => 'Melihat daftar Guru',
                'action' => 'index',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            128 => 
            array (
                'id' => '9cc1a0af-59e7-4706-8299-a52433aab7d4',
                'slug' => 'guru.create',
                'nama' => 'Menampilkan form tambah Guru',
                'action' => 'create',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            129 => 
            array (
                'id' => '9cc1a0af-5b13-4f7a-bbb0-7a96c339c93a',
                'slug' => 'guru.store',
                'nama' => 'Menyimpan form tambah Guru',
                'action' => 'store',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            130 => 
            array (
                'id' => '9cc1a0af-5c31-4140-9d93-296836a0fc6c',
                'slug' => 'guru.show',
                'nama' => 'Menampilkan detail Guru',
                'action' => 'show',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            131 => 
            array (
                'id' => '9cc1a0af-5d45-4221-b4fc-41d3bc17b523',
                'slug' => 'guru.edit',
                'nama' => 'Menampilkan form edit Guru',
                'action' => 'edit',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            132 => 
            array (
                'id' => '9cc1a0af-5e41-4648-bfb4-90dbb1b767b7',
                'slug' => 'guru.update',
                'nama' => 'Menyimpan form edit Guru',
                'action' => 'update',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            133 => 
            array (
                'id' => '9cc1a0af-5f63-42a3-9328-da0d4ddbdedc',
                'slug' => 'guru.destroy',
                'nama' => 'Menghapus Guru',
                'action' => 'destroy',
                'group' => 'guru',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:24',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            134 => 
            array (
                'id' => '9cc1a0b7-f625-4bb7-b426-5b71ec977f0b',
                'slug' => 'siswa.index',
                'nama' => 'Melihat daftar Siswa',
                'action' => 'index',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            135 => 
            array (
                'id' => '9cc1a0b8-07ed-4b08-a246-f645136ac985',
                'slug' => 'siswa.create',
                'nama' => 'Menampilkan form tambah Siswa',
                'action' => 'create',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            136 => 
            array (
                'id' => '9cc1a0b8-0e4e-4bc3-a890-70ad41a9bb51',
                'slug' => 'siswa.store',
                'nama' => 'Menyimpan form tambah Siswa',
                'action' => 'store',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            137 => 
            array (
                'id' => '9cc1a0b8-0f69-40e8-b3f0-f883300aca22',
                'slug' => 'siswa.show',
                'nama' => 'Menampilkan detail Siswa',
                'action' => 'show',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            138 => 
            array (
                'id' => '9cc1a0b8-1067-45c5-8846-33c14ce28492',
                'slug' => 'siswa.edit',
                'nama' => 'Menampilkan form edit Siswa',
                'action' => 'edit',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            139 => 
            array (
                'id' => '9cc1a0b8-116e-4044-b22a-dacc28d34e20',
                'slug' => 'siswa.update',
                'nama' => 'Menyimpan form edit Siswa',
                'action' => 'update',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            140 => 
            array (
                'id' => '9cc1a0b8-12ad-4d16-b520-caf000a65302',
                'slug' => 'siswa.destroy',
                'nama' => 'Menghapus Siswa',
                'action' => 'destroy',
                'group' => 'siswa',
                'description' => NULL,
                'created_at' => '2024-08-13 13:06:30',
                'updated_at' => '2024-08-13 13:06:51',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            141 => 
            array (
                'id' => '9cc744eb-c726-491c-a13b-4bee76547d04',
                'slug' => 'course.index',
                'nama' => 'Melihat daftar Course',
                'action' => 'index',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            142 => 
            array (
                'id' => '9cc744eb-d913-4866-8c02-cfff5cd80233',
                'slug' => 'course.create',
                'nama' => 'Menampilkan form tambah Course',
                'action' => 'create',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            143 => 
            array (
                'id' => '9cc744eb-da54-4b59-8842-f7ac119c37f1',
                'slug' => 'course.store',
                'nama' => 'Menyimpan form tambah Course',
                'action' => 'store',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            144 => 
            array (
                'id' => '9cc744eb-db67-4e27-b5ff-571d2dcfec38',
                'slug' => 'course.show',
                'nama' => 'Menampilkan detail Course',
                'action' => 'show',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            145 => 
            array (
                'id' => '9cc744eb-dc7b-47c7-9e80-711a9338fee7',
                'slug' => 'course.edit',
                'nama' => 'Menampilkan form edit Course',
                'action' => 'edit',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            146 => 
            array (
                'id' => '9cc744eb-dd9b-4ac6-ae9a-559ffc51fee0',
                'slug' => 'course.update',
                'nama' => 'Menyimpan form edit Course',
                'action' => 'update',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            147 => 
            array (
                'id' => '9cc744eb-debc-4d05-a5ce-224689639c83',
                'slug' => 'course.destroy',
                'nama' => 'Menghapus Course',
                'action' => 'destroy',
                'group' => 'course',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:47',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            148 => 
            array (
                'id' => '9cc744fa-ca99-41c0-b8eb-270f215dde77',
                'slug' => 'coursedetail.index',
                'nama' => 'Melihat daftar Coursedetail',
                'action' => 'index',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            149 => 
            array (
                'id' => '9cc744fa-dfbc-4ddb-9645-25530798e4b9',
                'slug' => 'coursedetail.create',
                'nama' => 'Menampilkan form tambah Coursedetail',
                'action' => 'create',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            150 => 
            array (
                'id' => '9cc744fa-e0fd-4615-9a6d-1dc602d3fc0c',
                'slug' => 'coursedetail.store',
                'nama' => 'Menyimpan form tambah Coursedetail',
                'action' => 'store',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            151 => 
            array (
                'id' => '9cc744fa-e207-4f66-9a35-736fba50190d',
                'slug' => 'coursedetail.show',
                'nama' => 'Menampilkan detail Coursedetail',
                'action' => 'show',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            152 => 
            array (
                'id' => '9cc744fa-e3a1-47de-a809-b8fd0ff7bb33',
                'slug' => 'coursedetail.edit',
                'nama' => 'Menampilkan form edit Coursedetail',
                'action' => 'edit',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            153 => 
            array (
                'id' => '9cc744fa-e4e0-4f52-9ac0-5763adfceec7',
                'slug' => 'coursedetail.update',
                'nama' => 'Menyimpan form edit Coursedetail',
                'action' => 'update',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
            154 => 
            array (
                'id' => '9cc744fa-e5d1-4229-af00-3d4de4fc5875',
                'slug' => 'coursedetail.destroy',
                'nama' => 'Menghapus Coursedetail',
                'action' => 'destroy',
                'group' => 'coursedetail',
                'description' => NULL,
                'created_at' => '2024-08-16 08:24:57',
                'updated_at' => '2024-08-16 08:29:08',
                'deleted_at' => NULL,
                'created_by' => 'Guest',
                'updated_by' => 'Guest',
                'deleted_by' => NULL,
            ),
        ));
        
        
    }
}